# Generated by Django 6.0.3 on 2026-03-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='contentitem',
            new_name='content_item',
        ),
    ]
